// tailwind.config.js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#e1e2e5',
        'secondary-container': '#00e3fd',
        'surface-tint': '#5f49c6',
        outline: '#797585',
        'tertiary-container': '#323333',
        'surface-container-high': '#e7e8eb',
        'primary-fixed-dim': '#c9beff',
        'primary-container': '#320e99',
        'surface-container-lowest': '#ffffff',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#1b0063',
        'on-primary-fixed-variant': '#472dad',
        'tertiary-fixed': '#e4e2e2',
        surface: '#f8f9fc',
        'surface-container-low': '#f2f3f6',
        error: '#ba1a1a',
        'on-secondary-fixed': '#001f24',
        'on-tertiary-container': '#9b9b9b',
        'on-error-container': '#93000a',
        'on-surface-variant': '#484553',
        'inverse-primary': '#c9beff',
        primary: '#1d0069',
        'on-secondary-container': '#00616d',
        'on-tertiary': '#ffffff',
        background: '#f8f9fc',
        'on-tertiary-fixed-variant': '#464747',
        'on-error': '#ffffff',
        'outline-variant': '#c9c4d5',
        'tertiary-fixed-dim': '#c7c6c6',
        'inverse-surface': '#2e3133',
        'primary-fixed': '#e5deff',
        'on-surface': '#191c1e',
        secondary: '#006875',
        'surface-container-highest': '#e1e2e5',
        'surface-container': '#edeef1',
        'on-tertiary-fixed': '#1b1c1c',
        'surface-bright': '#f8f9fc',
        'inverse-on-surface': '#f0f1f4',
        'secondary-fixed': '#9cf0ff',
        'on-secondary': '#ffffff',
        tertiary: '#1d1e1e',
        'on-background': '#191c1e',
        'secondary-fixed-dim': '#00daf3',
        'on-secondary-fixed-variant': '#004f58',
        'on-primary-container': '#9d8bff',
        'error-container': '#ffdad6',
        'surface-dim': '#d9dadd',
      },
      fontFamily: {
        sans: ['var(--font-ibm-plex-sans-arabic)', 'IBM Plex Sans Arabic', 'sans-serif'],
      },
      fontSize: {
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '60px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
      },
      spacing: {
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        gutter: '24px',
        unit: '8px',
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}